#!/usr/bin/env python3
"""Reference/provenance validation checks for cmrdesign.

These checks are intentionally separate from cross-language parity fixtures.
They compare package outputs to closed-form calculations, archived reference
values, and extension identities that are not regenerated by the package.
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PYTHON_SRC = ROOT / "python" / "src"
if PYTHON_SRC.exists():
    sys.path.insert(0, str(PYTHON_SRC))

import numpy as np

import cmrdesign as cmr

FAILURES: list[str] = []


def record_failure(message: str) -> None:
    FAILURES.append(message)


def assert_close(actual, expected, label: str, tol: float = 1e-10) -> None:
    actual_arr = np.asarray(actual, dtype=float).reshape(-1)
    expected_arr = np.asarray(expected, dtype=float).reshape(-1)
    if actual_arr.shape != expected_arr.shape:
        record_failure(
            f"{label} shape mismatch: got {actual_arr.shape}, "
            f"expected {expected_arr.shape}"
        )
        return
    delta = float(np.max(np.abs(actual_arr - expected_arr)))
    if not math.isfinite(delta) or delta > tol:
        record_failure(f"{label} mismatch: max |actual - expected| = {delta} > {tol}")


def assert_equal(actual, expected, label: str) -> None:
    if actual != expected:
        record_failure(f"{label} mismatch: got {actual!r}, expected {expected!r}")


def run_check(name: str, fn) -> None:
    try:
        fn()
    except Exception as exc:  # pragma: no cover - failure reporting path
        record_failure(f"{name} errored: {exc}")
        print(f"[FAIL] {name}")
    else:
        print(f"[PASS] {name}")


def reference_regret(pi: float, v1: float, v0: float) -> float:
    return v1 / pi + v0 / (1 - pi) - (math.sqrt(v1) + math.sqrt(v0)) ** 2


def reference_two_arm_cmr(rectangle: dict[str, float]) -> dict:
    score_treatment = math.sqrt(rectangle["v_u1"]) + math.sqrt(rectangle["v_l1"])
    score_control = math.sqrt(rectangle["v_u0"]) + math.sqrt(rectangle["v_l0"])
    score_total = score_treatment + score_control
    pi = score_treatment / score_total if score_total > 0 else 0.5
    regrets = {
        "treatment_high_control_low": reference_regret(
            pi,
            rectangle["v_u1"],
            rectangle["v_l0"],
        ),
        "treatment_low_control_high": reference_regret(
            pi,
            rectangle["v_l1"],
            rectangle["v_u0"],
        ),
    }
    return {"pi": pi, "u_cmr": max(regrets.values()), "regrets": regrets}


def reference_mp_bounds(y, beta_l: float, beta_u: float) -> dict[str, float]:
    y_arr = np.asarray(y, dtype=float)
    vhat = float(np.var(y_arr, ddof=1))
    sdhat = math.sqrt(max(vhat, 0.0))
    lower = (
        0.0
        if beta_l <= 0
        else max(0.0, sdhat - math.sqrt(2 * math.log(1 / beta_l) / (y_arr.size - 1)))
        ** 2
    )
    upper = (
        0.25
        if beta_u <= 0
        else (sdhat + math.sqrt(2 * math.log(1 / beta_u) / (y_arr.size - 1))) ** 2
    )
    return {
        "L": float(np.clip(lower, 0, 0.25)),
        "U": float(np.clip(upper, 0, 0.25)),
        "vhat": vhat,
    }


def reference_bernoulli_rho(v: float) -> float:
    if v >= 0.25:
        return 0.5
    return 2 * v / (1 + math.sqrt(max(0.0, 1 - 4 * v)))


def binom_pmf(k: int, m: int, p: float) -> float:
    return math.comb(m, k) * (p**k) * ((1 - p) ** (m - k))


def reference_folded_pmf(v: float, m: int) -> np.ndarray:
    rho = reference_bernoulli_rho(v)
    values = []
    for j in range(math.floor(m / 2) + 1):
        p_left = binom_pmf(j, m, rho)
        p_right = 0.0 if 2 * j == m else binom_pmf(m - j, m, rho)
        values.append(p_left + p_right)
    out = np.asarray(values, dtype=float)
    return out / np.sum(out)


def check_two_arm_closed_form() -> None:
    rect = {"v_l1": 0.01, "v_u1": 0.09, "v_l0": 0.04, "v_u0": 0.16}
    expected = reference_two_arm_cmr(rect)
    fit = cmr.cmr_two_arm_from_rectangle(rect)
    assert_close(fit.pi, expected["pi"], "two-arm pi", tol=1e-12)
    assert_close(fit.u_cmr, expected["u_cmr"], "two-arm U_CMR", tol=1e-12)
    actual_regrets = [
        fit.extra["corner_regrets"]["treatment_high_control_low"],
        fit.extra["corner_regrets"]["treatment_low_control_high"],
    ]
    expected_regrets = [
        expected["regrets"]["treatment_high_control_low"],
        expected["regrets"]["treatment_low_control_high"],
    ]
    assert_close(actual_regrets, expected_regrets, "two-arm corner regrets", tol=1e-12)


def check_mtr_archived_values() -> None:
    pattern = [0.05 + 0.10 * i for i in range(10)]
    y = pattern * 50
    bounds = cmr.variance_bounds_martinez_taboada_ramdas(
        y,
        beta_l=0.0125,
        beta_u=0.0125,
    )
    assert_close(bounds["L"], 0.04690604657062841, "MTR L", tol=1e-12)
    assert_close(bounds["U"], 0.10320241415971833, "MTR U", tol=1e-12)
    assert_close(
        bounds["statistic"]["upper_center"],
        0.08352562992913529,
        "MTR upper center",
        tol=1e-12,
    )
    assert_close(
        bounds["statistic"]["alpha_lower_variance"],
        0.00625,
        "MTR alpha lower variance",
        tol=1e-15,
    )
    assert_close(
        bounds["statistic"]["alpha_lower_mean"],
        0.00625,
        "MTR alpha lower mean",
        tol=1e-15,
    )


def check_bernoulli_formula() -> None:
    expected = reference_folded_pmf(v=0.10, m=4)
    actual = cmr.folded_binomial_pmf(v=0.10, m=4)
    assert_close(actual, expected, "folded-binomial pmf", tol=1e-12)

    y = [0, 1, 0, 0, 1, 0, 0, 0]
    bounds = cmr.variance_bounds_bernoulli_exact(y, beta_l=0.0125, beta_u=0.0125)
    assert_close(bounds["vhat"], 2 * (8 - 2) / (8 * 7), "folded sample variance")
    assert_equal(bounds["method"], "bernoulli", "Bernoulli method")


def check_multiarm_collapsed() -> None:
    variances = {"0": 0.04, "1": 0.09, "2": 0.16}
    scores = {
        "0": math.sqrt(2 * variances["0"]),
        "1": math.sqrt(variances["1"]),
        "2": math.sqrt(variances["2"]),
    }
    total = sum(scores.values())
    expected_pi = {key: value / total for key, value in scores.items()}
    rect = {
        "v_l0": 0.04,
        "v_u0": 0.04,
        "v_l1": 0.09,
        "v_u1": 0.09,
        "v_l2": 0.16,
        "v_u2": 0.16,
    }
    fit = cmr.cmr_multiarm_from_rectangle(rect)
    assert_close(
        [fit.pi[key] for key in expected_pi],
        [expected_pi[key] for key in expected_pi],
        "multi-arm collapsed pi",
    )
    assert_close(fit.u_cmr, 0.0, "multi-arm collapsed U_CMR", tol=1e-9)


def check_stratified_collapsed() -> None:
    strata_share = {"A": 0.6, "B": 0.4}
    variances = {
        "1": {"A": 0.04, "B": 0.16},
        "0": {"A": 0.09, "B": 0.01},
    }
    scores = {
        "1:A": strata_share["A"] * math.sqrt(variances["1"]["A"]),
        "0:A": strata_share["A"] * math.sqrt(variances["0"]["A"]),
        "1:B": strata_share["B"] * math.sqrt(variances["1"]["B"]),
        "0:B": strata_share["B"] * math.sqrt(variances["0"]["B"]),
    }
    total = sum(scores.values())
    expected_pi = {key: value / total for key, value in scores.items()}
    rect = {"lower": variances, "upper": variances}
    fit = cmr.cmr_stratified_from_rectangle(rect, strata_share)
    assert_close(
        [fit.pi[key] for key in expected_pi],
        [expected_pi[key] for key in expected_pi],
        "stratified collapsed pi",
    )
    assert_close(fit.u_cmr, 0.0, "stratified collapsed U_CMR", tol=1e-9)


def check_multiple_outcomes_coprimary() -> None:
    pattern_treat = np.asarray(
        [[0.20, 0.10], [0.40, 0.20], [0.60, 0.70], [0.80, 0.90]],
        dtype=float,
    )
    pattern_control = np.asarray(
        [[0.30, 0.20], [0.45, 0.25], [0.55, 0.35], [0.70, 0.40]],
        dtype=float,
    )
    y = np.vstack([np.tile(pattern_treat, (50, 1)), np.tile(pattern_control, (50, 1))])
    d = np.asarray([1] * 200 + [0] * 200)
    weights = np.asarray([0.7, 0.3])
    beta = 0.10 / (4 * y.shape[1])
    treatment_bounds = [
        reference_mp_bounds(y[d == 1, col], beta, beta) for col in range(y.shape[1])
    ]
    control_bounds = [
        reference_mp_bounds(y[d == 0, col], beta, beta) for col in range(y.shape[1])
    ]
    expected_rectangle = {
        "v_l1": sum(weights[col] * treatment_bounds[col]["L"] for col in range(2)),
        "v_u1": sum(weights[col] * treatment_bounds[col]["U"] for col in range(2)),
        "v_l0": sum(weights[col] * control_bounds[col]["L"] for col in range(2)),
        "v_u0": sum(weights[col] * control_bounds[col]["U"] for col in range(2)),
    }
    fit = cmr.cmr_multiple_outcomes(
        y,
        d,
        weights=weights,
        estimand="coprimary",
        alpha=0.10,
        method="bounded",
    )
    assert_close(
        [fit.rectangle[key] for key in expected_rectangle],
        [expected_rectangle[key] for key in expected_rectangle],
        "multiple-outcome coprimary rectangle",
    )


def check_proxy_bridge() -> None:
    proxy_y = [0, 1, 0, 1, 1, 0, 0, 1]
    d = [1, 1, 1, 1, 0, 0, 0, 0]
    zeta = {"treatment": 0.04, "control": 0.06}
    fit = cmr.cmr_proxy(proxy_y, d, zeta=zeta, method="bernoulli", alpha=0.05)
    proxy_rect = fit.confidence_set.extra["bridge"]["proxy_rectangle"]
    expected = {
        "v_l1": max(0.0, math.sqrt(proxy_rect["v_l1"]) - zeta["treatment"]) ** 2,
        "v_u1": min(0.5, math.sqrt(proxy_rect["v_u1"]) + zeta["treatment"]) ** 2,
        "v_l0": max(0.0, math.sqrt(proxy_rect["v_l0"]) - zeta["control"]) ** 2,
        "v_u0": min(0.5, math.sqrt(proxy_rect["v_u0"]) + zeta["control"]) ** 2,
    }
    assert_close(
        [fit.rectangle[key] for key in expected],
        [expected[key] for key in expected],
        "proxy widened rectangle",
    )


def check_planning_formulas() -> None:
    assert_close(cmr.break_even_pilot_share(0.5, 0.25), 0.1, "break-even pilot share")
    assert_equal(cmr.activation_threshold_bounded(alpha=0.05), 72, "bounded activation")
    assert_equal(cmr.activation_threshold_bernoulli(alpha=0.05), 4, "bernoulli activation")
    plan = cmr.cmr_plan(
        n=1000,
        sigma1=0.5,
        sigma0=0.25,
        alpha=0.05,
        method="bounded",
        desired_pilot=100,
    )
    assert_equal(plan["desired_status"], "above_break_even_cap", "desired pilot status")
    assert_equal(plan["band"]["min_feasible"], 72, "planning min feasible")
    assert_equal(plan["band"]["max_feasible"], 98, "planning max feasible")


def main() -> int:
    checks = [
        ("two-arm closed-form CMR", check_two_arm_closed_form),
        ("MTR archived old-implementation reference values", check_mtr_archived_values),
        ("exact Bernoulli folded-binomial formula", check_bernoulli_formula),
        ("collapsed shared-control multi-arm reduces to Neyman", check_multiarm_collapsed),
        ("collapsed stratified rectangle reduces to stratified Neyman", check_stratified_collapsed),
        (
            "multiple-outcome co-primary rectangle from independent MP endpoints",
            check_multiple_outcomes_coprimary,
        ),
        ("proxy bridge widens standard-deviation intervals by zeta", check_proxy_bridge),
        ("Appendix E pilot-planning formulas", check_planning_formulas),
    ]
    for name, fn in checks:
        run_check(name, fn)

    if FAILURES:
        print("\nReference validation failures:", file=sys.stderr)
        for failure in FAILURES:
            print(f"- {failure}", file=sys.stderr)
        return 1
    print("Reference/provenance validation checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
